---
- name: "Ensure installers directory is present"
  file:
    path: "{{ rustup_src_path | dirname }}"
    state: directory
    owner: root
    group: root
  become: yes
  tags:
    - directory

- name: "Get latest Rust installer"
  get_url:
    url: https://static.rust-lang.org/rustup.sh
    dest: "{{ rustup_src_path }}"
    mode: "u=rwx,go="
    owner: root
    group: root
  become: yes
  register: rust_installer
  notify: "rustup"
  tags:
    - install
