- name: "Run latest Rust installer"
  command: "bash {{ rustup_src_path }}"
  become: yes
  listen: "rustup"
  tags:
    - compile

- name: "Install Rust packages"
  command: "/usr/local/bin/cargo install --force {{ item }}"
  become: no
  with_items: "{{ rust_packages }}"
  listen:
    - "rustup"
    # todo: package notification
  tags:
    - dependency
    - install
    - rust
